server:
    port: 8050 #8181
spring:
    application:
        name: myzuul

eureka:
    client:
        serviceUrl:
            defaultZone: http://user:123456@localhost:8761/eureka  #注册 中心已经开启认证
    instance:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  routes:
    myclient:
      path: /**
      serviceId:  myclient