server:
    port: 8761 #端口

security:
    basic:
        enabled: true #开启认证
    user:
        name: user #认证名称
        password: 123456 #认证密码

eureka:
    instance:
        hostname: localhost #服务host
    client:
        registerWithEureka: false #关闭自我注册
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
   routes:
       baidu:
           path: /myserver/demo/**
           url: http://127.0.0.1:8090/myserver/demo/