server:
    port: 9000 #端口
spring:
    application:
        name: myeureka

security:
    basic:
        enabled: true #开启认证
    user:
        name: user #认证名称
        password: 123456 #认证密码

eureka:
    instance:
        hostname: localhost #服务host
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/myeureka/
        register-with-eureka: false
        fetch-registry: false
